# Generated by Django 4.1 on 2023-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.BooleanField(choices=[('Attend Quiz', 'Attend Quiz'), ('Present Quiz', 'Present Quiz')], default=False),
        ),
    ]
