# Generated by Django 4.1 on 2023-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quiz_name',
            field=models.CharField(max_length=50),
        ),
    ]
