# Generated by Django 4.1 on 2023-06-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_customuser_gender_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Attend Quiz', 'Attend Quiz'), ('Present Quiz', 'Present Quiz')], default=False, max_length=50),
        ),
    ]
