# Generated by Django 4.1 on 2023-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('number_of_questions', models.IntegerField()),
                ('required_score_to_pass', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
